### ISSUE TITLE
[ Umbrella issue] Convert site to docsy theme

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#126]
This is a large restructure of the current project. [Docsy](https://docsy.dev/) is a hugo theme and very easy to extend. 

The primary kubernetes website (https://kubernetes.io) is being converted to use the same backend theme. ([preview](https://kubernetes-hugo-staging.netlify.com/docs/home/)).

It is also being used by [minikube](https://github.com/kubernetes/minikube) for their documentation (https://minikube.sigs.k8s.io) with a few other subprojects interested in using it as well.

For the contributor site a separate [docsy branch](https://github.com/kubernetes-sigs/contributor-site/tree/docsy) has been made.
For a WIP preview: see this PR: https://github.com/kubernetes-sigs/contributor-site/pull/122 ([site preview](https://deploy-preview-122--kubernetes-contributor.netlify.com/))

These are the issues that should be resolved before the docsy branch is promoted to master and becomes the default:
- [x] [SCSS generation error](https://github.com/kubernetes-sigs/contributor-site/issues/123)
- [x] [External content needs restructuring](https://github.com/kubernetes-sigs/contributor-site/issues/124)
- [x] [Some pages are not being rendered correctly](https://github.com/kubernetes-sigs/contributor-site/issues/125)

**Comment by mrbobbytables** [comment]
All items have been addressed in the [WIP PR](https://github.com/kubernetes-sigs/contributor-site/pull/122).
Going to go ahead and close this out, as the PR is ready to merge.

close

**Comment by mrbobbytables** [comment]
woops

/close
