### ISSUE TITLE
Contributor site launch list

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#129]
List of items that need to be resolved before go live. This may be updated as needed with further items as they're discovered.

- [x] **Fix bug with kubernetes  icon in top left** (#131)
   The icon appears white in the netlify preview but does seem to work in local preview
- [x] **Add release page for 1.19 to the resources category** (#133)
   We had a test one configured for the 1.18 release. We should now update it for 1.19
- [x] **Event pages need to be updated.** (#134)
  Information for MoC and the community meeting is out of date.
- [X] **Add comment on the CoC page with a link to the source of truth.** (#132)
  As we have no control over the actual CoC page to add metadata etc, our own copy is needed. A note regarding that that the origin is the source of truth if it is ever out of date is needed.
- [X] [**Add contributor calendar**](https://github.com/kubernetes-sigs/contributor-site/issues/127) (#136)
  We had a calendar previously under the old version of the site, however the css and other components did not work well under the new theme.
- [x] [**Finish updating contributor guide**](https://github.com/kubernetes-sigs/contributor-site/issues/86)
  The contributor guide pages need to have their weights updated along with descriptions added to their metadata
- [x] [**Transfer and configure domain**](https://github.com/kubernetes-sigs/contributor-site/issues/98)
  Needed to launch with the kubernetes.dev domain.

**Once all components are completed we will soft launch and share the link with the ContribEx mailing list. After 1 week if there are no issues, we will go live with the full launch and announce through general comms channels.**

/milestone v1.19
/priority important-soon
/help wanted

**Comment by jonasrosland** [comment]
The first item, the icon being the wrong color, might be related to this: https://github.com/gohugoio/hugo/issues/6475
An easy test would be to try it without using `minify`, see if that helps.

**Comment by mrbobbytables** [comment]
All items have been completed, go live date scheduled for the 24th
